vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-spring-initializr
    - redhat.vscode-xml
    - redhat.fabric8-analytics
    # - pivotal.vscode-boot-dev-pack
    # - pivotal.vscode-spring-boot
    - vscjava.vscode-spring-boot-dashboard
    
